name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy dist to EC2
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" dist/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/frontend/dist/

      - name: (Optional) Restart Nginx container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker restart nginx-proxy
          EOF
